version: '3.2'

services:
  python-deskew-mrz:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./images
        target: /usr/src/app/data
  node-image-service:
    build:
      context: ./ts-node
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./images
        target: /usr/src/app/data
    ports:
      - 80:8080
# volumes:
#   ./images: image-shared-folder